// BLOG
export const RETRIEVE_POSTS_SUCCESS = 'RETRIEVE_POSTS_SUCCESS';
export const RETRIEVE_PAGES_SUCCESS = 'RETRIEVE_PAGES_SUCCESS';

// USERS
export const RETRIEVE_USERS_SUCCESS = 'RETRIEVE_USERS_SUCCESS';
