module.exports = [
  {
    name: 'Gist organizer',
    slug: 'gist-organizer',
    year: '2017',
    in_progress: true,
    technos: ['ReactJS'],
    purpose:
      'I want to create a simple interface to manage my Gist, create collections, add tags for better search',
  },
  {
    name: 'Feedly - Landing page',
    slug: 'feedly-landing',
    url: 'https://feedly.com/i/landing',
    visual: 'works/feedly-landing.png',
    year: '2016',
    in_progress: false,
    technos: ['ReactJS'],
    purpose: 'Re-degign of the Feedly blog by creating our own template.',
  },
  {
    name: 'Feedly - blog redesign',
    slug: 'feedly-blog',
    url: 'https://blog.feedly.com',
    visual: 'works/feedly-blog.png',
    year: '2016',
    in_progress: false,
    technos: ['Wordpress'],
    purpose: 'Redesign of the Feedly blog by creating our own template.',
  },
  {
    name: 'Feedly - Save to Knowledge Boards extension',
    slug: 'feedly-extension',
    url: 'https://blog.feedly.com',
    visual: 'works/feedly-save-to-kb.png',
    year: '2016',
    in_progress: false,
    technos: ['ReactJS'],
    purpose:
      "It's easly to add an article into a Knowledge Board in Feedly with the new extension. Available on Firefox, Chrome and Safari.",
  },
  {
    name: 'Franfinance',
    slug: 'franfinance',
    url: 'https://blog.feedly.com',
    visual: 'works/franfinance.png',
    year: '2015',
    in_progress: false,
    technos: ['AngularJS', 'Drupal'],
    purpose: 'Re-design of the Franfinance website.',
  },
  {
    name: 'Arval',
    slug: 'arval',
    url: 'https://www.arval.co.uk/',
    visual: 'works/arval.png',
    year: '2015',
    in_progress: false,
    technos: ['Drupal'],
    purpose: 'Re-design all the Arval websites.',
  },
];
